name: cron-check-upstream
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  check_upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - id: check
      run: ./check_latest_version.sh 'valkey-io/valkey' 'bookworm' 'valkey-server'
      shell: bash
    - name: Trigger build workflow
      if: steps.check.outputs.vercomp == 'newer'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow run .github/workflows/build.yml --ref main -F valkey_tag=${{ steps.check.outputs.remote_current_release }}

